# Generated by Django 2.2.27 on 2022-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='position',
            field=models.CharField(choices=[('PRO', 'Professor'), ('POS', 'Postdoctoral Researcher'), ('PHD', 'Ph.D. Student'), ('MAS', 'Master Student'), ('INT', 'Integrated Ph.D. Student'), ('VIS', 'Visiting Researcher')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('PRO', 'Professor'), ('POS', 'Postdoctoral Researcher'), ('PHD', 'Ph.D. Student'), ('MAS', 'Master Student'), ('INT', 'Integrated Ph.D. Student'), ('VIS', 'Visiting Researcher')], max_length=3),
        ),
    ]
