# Generated by Django 2.2.27 on 2022-03-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220318_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='published_date',
            field=models.DateField(help_text='Date of publication, used for sorting. Enter the conference start date for conferences.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='venue',
            field=models.TextField(help_text='Use abbreviations for top-tier AI conferences. Add parentheses around the publication year for journal articles. E.g., \'NeurIPS (Oral) 2020\', \'NeurIPS Workshop: "Competition Track on Black-Box Optimization Challenge" 2020\', \'Nature (2020)\', \'IEEE Transactions on Wireless Communications (2020)\''),
        ),
    ]
