# Generated by Django 2.2.5 on 2022-04-03 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, default='Artificial Intelligence', help_text="If you are a graduate alumni, enter the name of your final degree. E.g., (MS in) 'Artificial Intelligence', (PhD in) 'Artificial Intelligence'. Do not include 'MS in', etc.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='KAIST AI', help_text="If you are a graduate student or alumni, enter your department at KAIST. E.g., 'KAIST AI', 'Industrial & Systems Engineering', 'Knowledge Service Engineering'.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_end_date',
            field=models.DateField(blank=True, help_text='If you are a graduate alumni, enter your final graduation date. Use YYYY-02-28 for Spring graduation and YYYY-08-31 for Fall graduation.', null=True, verbose_name='Depart date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_start_date',
            field=models.DateField(help_text='If you are a graduate student or alumni, enter your admission date for your current course. Use YYYY-03-01 for Spring admission and YYYY-09-01 for Fall admission.', null=True, verbose_name='Join date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='visiting_title',
            field=models.CharField(blank=True, help_text="If you are a visiting reserach, enter a custom title. Please use abbreviations for department names. E.g., 'UG at KAIST CS', 'PhD at SNU CS'.", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PublicationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_tags_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tags', to='core.PublicationTag'),
        ),
    ]
