# Generated by Django 2.2.5 on 2022-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='previous_members',
            field=models.TextField(default='', help_text="E.g., 'Yoshua Bengio, Yann LeCun and Geoffrey Hinton'"),
            preserve_default=False,
        ),
    ]
