# Generated by Django 2.2.5 on 2022-07-24 17:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220419_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=core.models.generate_admin_token, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GPUStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('server_name', models.TextField(max_length=100)),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'GPU status',
            },
        ),
    ]
