# Generated by Django 2.2.5 on 2023-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230204_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='research_topics',
            field=models.TextField(blank=True, help_text='Examples: CV, NLP, Theory, Data Centric, FL, RL, GNN, Few-Shot, LLM, AutoML, SSL.', max_length=500, null=True),
        ),
    ]
