# Generated by Django 2.2.28 on 2023-02-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230209_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='core.PublicationTag'),
        ),
    ]
