# Generated by Django 2.2.28 on 2023-10-31 06:17

from django.db import migrations, models
import django.utils.timezone


def copy_accepted_date_from_published_date(apps, schema_editor):
    Publication = apps.get_model('core', 'Publication')
    for publication in Publication.objects.all():
        publication.accepted_date = publication.published_date
        publication.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_auto_20230215_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='accepted_date',
            field=models.DateField(default=django.utils.timezone.now,
                                   help_text='Date of acceptance, used for sorting.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_date',
            field=models.DateField(
                help_text='Date of publication, used for year grouping. Enter the conference start date for conferences.'),
        ),
        migrations.RunPython(copy_accepted_date_from_published_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='current_position',
            field=models.CharField(blank=True,
                                   help_text="If you are a graduate alumni, enter your current job. Examples: 'Research Scientist, Google', 'Assistant Professor, Seoul National University'",
                                   max_length=100, null=True),
        ),
    ]
