from django.shortcuts import render

# Create your views here.
def home(request):
    data = {
        "project_list": [
            {'title': "Development of XAI-based Technology for Smart Energe Platform", "detail": "This project aims at KEPCO to form a cluster of five schools including KAIST to propose XAI-based smart energy platform technology. In our lab, we study to solve bottlenecks caused by gradient sharing that occurs when training deep learning models with large amounts of data. To solve this problem, we compress the gradient using methods such as Random Projection and Sequential Trasmitting Method.", "img": "images/project/proj_kepco.png"},
            {'title': "AutoML", "detail": "The neural architecture search (NAS) has been a great success in a variety of applications such as image classification and natural language processing. Despite huge success, it faces a challenge that takes too much resource budgets (e.g.,  computational costs and storage), which stems from the vastness of NAS's search space. In this project, we aim to reduce the tremendous resource budget required due to the large search space.", "img": "images/project/proj_etri.png"},
            {'title': "Developing Models for Predicting Properties of Compounds using Artificial Neural Network", 'detail': "Properties of tire compounds are closely related to the performance of tire. Therefore, one of the goals of this project is to develop models to predict properties of the compounds. Moreover, we aim to develop inverse design models to suggest proper compounds for the target properties. We also propose automatic systems for building AI models.",  "img": "images/project/proj_hankooktire.png"},
            {'title': "Explainable intelligent system for optimal strategy in battles", 'detail': "Recently, artificial neural networks have shown remarkable successes with huge datasets. However, with scarce data, artificial neural networks are terrible.  In military situations, unfortunately, it is difficult to obtain a large training dataset.  Military cases also require to explain the decisions that the algorithm generates, which is very tricky with general artificial neural networks. In this project, we address these problems and design new approaches using Bayesian frameworks.",  "img": "images/project/proj_add.png"},
            {'title': "Alpha Weather", 'detail': "This project aims to solve the short-term prediction of precipitation(rainfall) in 6 hours. Although many meteorologists have provided a reasonably accurate forecast of long-term precipitation, the short-term prediction remains a big challenge. We anticipate an accurate short-term prediction by using artificial intelligence like AlphaGo. In this project, we define useful input data to be utilized for the short-term precipitation and propose machine learning algorithms predicting short-term rainfalls.",  "img": "images/project/proj_weather.png"},
            {'title': "Efficient Representation Learning Algorithm for Unlabeled Data", 'detail': "We often unavailable to obtain enough labeled data for our target task(ex. Image Classification) in most real-world cases. Some recent works address the data shortage by proposing un-, semi-, or self- supervised learning methods that utilize unlabeled data to improve the performance in target task without or with only a few amounts of labeled data. In this project, we extend those methods to build a data and training efficient algorithm to cope with various real-world constraints. We start by vision data and then consider sequential data.",  "img": "images/project/proj_hynix.png"},
        ]
    }

    return render(request, 'home.html', data)

